# 适配诊断：分辨率策略 + 各层世界缩放 + StartPage 内容可见性 + 弹窗尺寸
sleep:4200
eval:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var v=cc.view;var o=[];o.push('vis='+JSON.stringify(v.getVisibleSize()));o.push('design='+JSON.stringify(v.getDesignResolutionSize()));o.push('scaleXY='+v.getScaleX().toFixed(3)+','+v.getScaleY().toFixed(3));o.push('pixel='+JSON.stringify(v.getVisibleSizeInPixel()));var cv=document.querySelector('canvas');if(cv){var r=cv.getBoundingClientRect();o.push('canvasRect='+Math.round(r.x)+','+Math.round(r.y)+' '+Math.round(r.width)+'x'+Math.round(r.height));}var cvn=cc.director.getScene().getChildByName('Canvas');var bl=find(cvn,'bootLayer');var bc=bl?bl.getComponent('Boot'):null;if(bc){bc.shown=bc.target=1;}return o.join(' | ');})()
sleep:1500
eval:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var pr=find(cv,'PageRoot');var sp=pr?find(pr,'StartPage'):null;if(!sp)return 'StartPage MISSING';var o=['sp.active='+sp.active+' scale='+sp.scale.x.toFixed(3)];['mask','Logo','SubTxt','TapTxt'].forEach(function(nm){var n=find(sp,nm);if(!n){o.push(nm+':MISSING');return;}var u=n.getComponent('cc.UITransform');var op=n.getComponent('cc.UIOpacity');var wp=n.getWorldPosition();var lb=n.getComponent('cc.Label');var spr=n.getComponent('cc.Sprite');var sf=spr&&spr.spriteFrame?spr.spriteFrame.name:'-';o.push(nm+':act='+n.active+' pos='+Math.round(n.position.x)+','+Math.round(n.position.y)+' wp='+Math.round(wp.x)+','+Math.round(wp.y)+' sc='+n.scale.x.toFixed(3)+' '+(u?Math.round(u.width)+'x'+Math.round(u.height):'?')+' opa='+(op?op.opacity:'-')+(lb?' txt="'+lb.string.slice(0,12)+'" fs='+lb.fontSize:'')+(spr?' sf='+sf:''));});return o.join(' | ');})()
shot:E:/LDC_Cocos_PJ/Cocos3X_2D/点瓶子_竖屏/项目/TapBottle/.workbuddy/_m3_startpage.png
jsclick:(function(){return [120,1100];})()
sleep:250
jsclick:(function(){return [360,640];})()
sleep:2000
eval:(function(){try{window.__tb.ui.settings();return 'settings=opened';}catch(e){return 'ERR '+e.message;}})()
sleep:1300
eval:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var dr=find(cv,'DialogRoot');var sd=dr?find(dr,'SettingDialog'):null;if(!sd)return 'SettingDialog MISSING';var o=[];var fr=find(sd,'frame');if(fr){var ws=fr.getWorldScale();var u=fr.getComponent('cc.UITransform');var wp=fr.getWorldPosition();o.push('frame ws='+ws.x.toFixed(3)+' w='+Math.round(u.width)+' wp='+Math.round(wp.x)+','+Math.round(wp.y));}var row=find(sd,'toggle_hide_income');if(row){var wsr=row.getWorldScale();var ur=row.getComponent('cc.UITransform');var wpr=row.getWorldPosition();o.push('row ws='+wsr.x.toFixed(3)+' w='+Math.round(ur.width)+' wp='+Math.round(wpr.x)+','+Math.round(wpr.y));var tt=find(row,'title');if(tt){o.push('title sc='+tt.scale.x.toFixed(3)+' '+(tt.getComponent('cc.UITransform')?Math.round(tt.getComponent('cc.UITransform').width)+'x'+Math.round(tt.getComponent('cc.UITransform').height):'?')+' txt="'+(tt.getComponent('cc.Label')?tt.getComponent('cc.Label').string.slice(0,10):'')+'"');}}var v=cc.view;o.push('scaleXY='+v.getScaleX().toFixed(3)+','+v.getScaleY().toFixed(3));return o.join(' | ');})()
shot:E:/LDC_Cocos_PJ/Cocos3X_2D/点瓶子_竖屏/项目/TapBottle/.workbuddy/_m3_settings.png
eval:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var bl=find(cv,'bootLayer');var pr=find(cv,'PageRoot');return 'boot='+(bl?bl.active:'gone')+' pageChildren='+(pr?pr.children.length:'?');})()
