# UI 预制体化验收（精简版）：绝对路径 shot + 最短等待
sleep:4200
eval:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var bl=find(cv,'bootLayer');var bc=bl?bl.getComponent('Boot'):null;if(!bc)return 'no Boot';bc.shown=bc.target=1;return 'ready='+bc.ready;})()
sleep:1500
eval:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var pr=find(cv,'PageRoot');var sp=pr?find(pr,'StartPage'):null;if(!sp)return 'StartPage MISSING pageChildren='+(pr?pr.children.map(function(c){return c.name;}).join(','):'?');return 'StartPage OK children='+sp.children.map(function(c){return c.name;}).join(',');})()
shot:E:/LDC_Cocos_PJ/Cocos3X_2D/点瓶子_竖屏/项目/TapBottle/.workbuddy/_m2_startpage.png
jsclick:(function(){return [120,1100];})()
sleep:250
jsclick:(function(){return [360,640];})()
sleep:2000
eval:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var bl=find(cv,'bootLayer');var bs=find(cv,'bottles');var pr=find(cv,'PageRoot');var sp=pr?find(pr,'StartPage'):null;var r='boot='+(bl?bl.active:'gone')+' bottles='+(bs?bs.children.length:'-')+' startPage='+(sp?('active='+sp.active):'gone');try{window.__tb.ui.settings();r+=' settings=opened';}catch(e){r+=' settings=ERR:'+e.message;}return r;})()
sleep:1300
eval:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var dr=find(cv,'DialogRoot');var sd=dr?find(dr,'SettingDialog'):null;if(!sd)return 'SettingDialog MISSING dialogChildren='+(dr?dr.children.map(function(c){return c.name;}).join(','):'?');var comp=sd.getComponent('SettingDialog');return 'SettingDialog OK toggles='+(comp&&comp.toggles?comp.toggles.length:'-')+' bindFn='+(comp&&comp.toggles[0]?typeof comp.toggles[0].bind:'-')+' steppers='+(comp&&comp.steppers?comp.steppers.length:'-');})()
shot:E:/LDC_Cocos_PJ/Cocos3X_2D/点瓶子_竖屏/项目/TapBottle/.workbuddy/_m2_settings.png
eval:(function(){try{window.__tb.uiMgr.hideDialog('SettingDialog');}catch(e){return 'ERR '+e.message;}try{window.__tb.ui.stats();return 'stats=opened';}catch(e){return 'ERR stats '+e.message;}})()
sleep:1300
eval:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var dr=find(cv,'DialogRoot');var d=dr?find(dr,'StatsDialog'):null;if(!d)return 'StatsDialog MISSING';var comp=d.getComponent('StatsDialog');var r='StatsDialog OK overview='+(comp&&comp.overview?comp.overview.length:'-');try{window.__tb.uiMgr.hideDialog('StatsDialog');window.__tb.ui.ach();r+=' ach=opened';}catch(e){r+=' ach=ERR:'+e.message;}return r;})()
sleep:1300
eval:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var dr=find(cv,'DialogRoot');var d=dr?find(dr,'AchDialog'):null;if(!d)return 'AchDialog MISSING dialogChildren='+(dr?dr.children.map(function(c){return c.name;}).join(','):'?');var comp=d.getComponent('AchDialog');try{window.__tb.uiMgr.hideDialog('AchDialog');}catch(e){}var dr2=find(cv,'DialogRoot');var pr=find(cv,'PageRoot');return 'AchDialog OK rows='+(comp&&comp.rows?comp.rows.length:'-')+' FINAL dialogChildren='+(dr2?dr2.children.length:'?')+' pageChildren='+(pr?pr.children.map(function(c){return c.name;}).join(','):'?');})()
shot:E:/LDC_Cocos_PJ/Cocos3X_2D/点瓶子_竖屏/项目/TapBottle/.workbuddy/_m2_final.png
