sleep:420
eval:(function(){var s=cc.director.getScene();var bl=s.getChildByName('Canvas').getChildByName('GameRoot').getChildByName('bootLayer');var bc=bl&&bl.getComponent('Boot');if(!bc)return 'NO_BOOT';var lr=bl.getChildByName('BootCtl').getChildByName('LoadingRoot');var inner=lr.getChildByName('Bar').getChildByName('Inner');var fill=inner.getChildByName('Fill');var rd=inner.getChildByName('Rider');return JSON.stringify({shown:Math.round(bc.shown*1000)/1000,target:Math.round(bc.target*1000)/1000,fillW:Math.round(fill.getComponent('cc.UITransform').width*10)/10,riderX:Math.round(rd.position.x*10)/10});})()
shot:E:/LDC_Cocos_PJ/Cocos3X_2D/点瓶子_竖屏/项目/TapBottle/.workbuddy/_m_load.png
sleep:2600
eval:(function(){var T='cc.UITransform';var bl=cc.director.getScene().getChildByName('Canvas').getChildByName('GameRoot').getChildByName('bootLayer');if(!bl)return 'BOOT_GONE';var bc=bl.getComponent('Boot');var ctl=bl.getChildByName('BootCtl');var lr=ctl.getChildByName('LoadingRoot');var bar=lr.getChildByName('Bar');var inner=bar.getChildByName('Inner');var fill=inner.getChildByName('Fill');var rd=inner.getChildByName('Rider');var o={scene:cc.director.getScene().name};o.shown=Math.round(bc.shown*1000)/1000;o.ready=bc.ready;o.barSize=[Math.round(bar.getComponent(T).width),Math.round(bar.getComponent(T).height)];o.innerW=Math.round(inner.getComponent(T).width*10)/10;o.innerH=Math.round(inner.getComponent(T).height*10)/10;o.innerXY=[Math.round(inner.position.x*10)/10,Math.round(inner.position.y*10)/10];o.innerAnchor=[inner.getComponent(T).anchorX,inner.getComponent(T).anchorY];o.fillW=Math.round(fill.getComponent(T).width*10)/10;o.riderX=Math.round(rd.position.x*10)/10;o.riderSize=[Math.round(rd.getComponent(T).width),Math.round(rd.getComponent(T).height)];o.trackSF=bar.getComponent('cc.Sprite').spriteFrame.name;var fs=fill.getComponent('cc.Sprite');o.fillType=fs.type;o.fillSF=fs.spriteFrame.name;o.txt=lr.getChildByName('LoadTxt').getComponent('cc.Label').string;o.fontSize=lr.getChildByName('LoadTxt').getComponent('cc.Label').fontSize;o.loadBottom=lr.getComponent('cc.Widget').bottom;o.loadActive=lr.active;o.titleActive=ctl.getChildByName('TitleRoot').active;return JSON.stringify(o);})()
shot:E:/LDC_Cocos_PJ/Cocos3X_2D/点瓶子_竖屏/项目/TapBottle/.workbuddy/_m_title2.png
eval:(function(){var bl=cc.director.getScene().getChildByName('Canvas').getChildByName('GameRoot').getChildByName('bootLayer');var bc=bl.getComponent('Boot');var ctl=bl.getChildByName('BootCtl');ctl.getChildByName('TitleRoot').active=false;var lr=ctl.getChildByName('LoadingRoot');lr.active=true;lr.getComponent('cc.UIOpacity').opacity=255;bc.shown=0.388;bc.target=0.388;bc.setFill(0.388);return 'FORCED 0.388';})()
sleep:260
shot:E:/LDC_Cocos_PJ/Cocos3X_2D/点瓶子_竖屏/项目/TapBottle/.workbuddy/_m_bar388.png
