sleep:9000
eval:(function(){var c=document.getElementById('GameCanvas');if(!c)return 'NO_CANVAS';var v=cc.view;var r=c.getBoundingClientRect();var s=cc.director.getScene();var cv=s.getChildByName('Canvas');var gr=cv?cv.getChildByName('GameRoot'):null;var bc=null;if(gr){var bl=gr.getChildByName('bootLayer');bc=bl?bl.getComponent('Boot'):null;}var f=window.__tb&&window.__tb.field&&window.__tb.field.I;var o={dpr:window.devicePixelRatio,css:[Math.round(r.width),Math.round(r.height)],attr:[c.width,c.height],vis:[Math.round(v.getVisibleSize().width),Math.round(v.getVisibleSize().height)],visPx:[Math.round(v.getVisibleSizeInPixel().width),Math.round(v.getVisibleSizeInPixel().height)],scene:s.name,bootReady:bc?bc.ready:-1,bootShown:bc?Math.round(bc.shown*100)/100:-1,bottles:f&&f.bottles?f.bottles.length:-1};var cr=gr&&gr.getChildByName('contentRoot');if(cr)o.crScale=[Math.round(cr.scale.x*1000)/1000,Math.round(cr.scale.y*1000)/1000];return JSON.stringify(o);})()
shot:E:/LDC_Cocos_PJ/Cocos3X_2D/点瓶子_竖屏/项目/TapBottle/.workbuddy/_d1_title.png
jsclick:(function(){var c=document.getElementById('GameCanvas');var r=c.getBoundingClientRect();return [r.width/2,r.height*0.5];})()
sleep:2500
eval:(function(){var s=cc.director.getScene();var gr=s.getChildByName('Canvas').getChildByName('GameRoot');var bl=gr.getChildByName('bootLayer');var f=window.__tb.field.I;var G=window.__tb.G;var o={bootGone:!bl||!bl.active,bottles:f.bottles.length,flips:G.data.stats.flips!==undefined?G.data.stats.flips:-1};return JSON.stringify(o);})()
shot:E:/LDC_Cocos_PJ/Cocos3X_2D/点瓶子_竖屏/项目/TapBottle/.workbuddy/_d2_game.png
jsclick:(function(){var c=document.getElementById('GameCanvas');var r=c.getBoundingClientRect();var k=r.width/720;var f=window.__tb.field.I;var b=f.bottles[0];if(!b)return [r.width/2,r.height*0.6];var wp=b.node.worldPosition;var cx=r.left+r.width/2, cy=r.top+r.height/2;return [Math.round(cx+wp.x*k),Math.round(cy-wp.y*k)];})()
sleep:1500
jsclick:(function(){var c=document.getElementById('GameCanvas');var r=c.getBoundingClientRect();var k=r.width/720;var f=window.__tb.field.I;var b=f.bottles[0];if(!b)return [r.width/2,r.height*0.6];var wp=b.node.worldPosition;var cx=r.left+r.width/2, cy=r.top+r.height/2;return [Math.round(cx+wp.x*k),Math.round(cy-wp.y*k)];})()
sleep:2500
eval:(function(){var f=window.__tb.field.I;var G=window.__tb.G;var o={bottles:f.bottles.length,flips:G.data.stats.flips!==undefined?G.data.stats.flips:-1,money:Math.round(G.data.money)};return JSON.stringify(o);})()
eval:(function(){var gr=cc.director.getScene().getChildByName('Canvas').getChildByName('GameRoot');var nav=gr.getChildByName('contentRoot').getChildByName('shakeHolder').getChildByName('uiLayer').getChildByName('navRoot');var out=[];function walk(n,d){if(d>3)return;var ut=n.getComponent('cc.UITransform');out.push(n.name+'@'+Math.round(n.worldPosition.x)+','+Math.round(n.worldPosition.y)+'|'+(ut?Math.round(ut.width)+'x'+Math.round(ut.height):'noUT')+'|act='+n.active);for(var i=0;i<n.children.length;i++)walk(n.children[i],d+1);}walk(nav,0);return out.join(' ; ');})()
