sleep:4500
eval:(function(){window.__errs=[];window.addEventListener('error',function(e){window.__errs.push(String(e.message||e.error));});return 'hooked';})()
sleep:4500
eval:(function(){var sc=cc.director.getScene().name;function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var vs=cc.view.getVisibleSize();var bar=find(cv,'Bar');var lr=find(cv,'LoadingRoot');var sp=find(cv,'StartPage');var out='scene='+sc+' vis='+vs.width.toFixed(0)+'x'+vs.height.toFixed(0)+' bar='+(bar?'yes':'no')+' loading='+(lr&&lr.activeInHierarchy?'on':'off')+' startPage='+(sp?'yes':'no');if(sp){var fit=sp.getChildByName('fit');var ut=sp.getComponent('cc.UITransform');out+=' spUT='+ut.width.toFixed(0)+'x'+ut.height.toFixed(0)+' fitScale='+(fit?fit.scale.x.toFixed(3):'-');var logo=find(sp,'Logo');if(logo){var wp=logo.getWorldPosition();out+=' logoWp='+wp.x.toFixed(0)+','+wp.y.toFixed(0);}}return out;})()
shot:E:/LDC_Cocos_PJ/Cocos3X_2D/点瓶子_竖屏/项目/TapBottle/.workbuddy/_m5_load.png
jsdrag:(function(){return [100,1100, 200,1100];})()
jsclick:(function(){var r=document.querySelector('canvas').getBoundingClientRect();return [r.x+r.width/2, r.y+r.height/2];})()
sleep:300
jsclick:(function(){var r=document.querySelector('canvas').getBoundingClientRect();return [r.x+r.width/2, r.y+r.height/2];})()
sleep:300
eval:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var sp=find(cv,'StartPage');var c=sp?sp.getComponent('StartPage'):null;var lr=find(cv,'LoadRoot');var lc=lr?lr.getComponent('LoadScene'):null;return 'scene='+cc.director.getScene().name+' spEntered='+(c?c.entered:'-')+' loadEntered='+(lc?lc.entered:'-');})()
sleep:2500
eval:(function(){var sc=cc.director.getScene().name;function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var vs=cc.view.getVisibleSize();var gr=find(cv,'gameRoot');var ur=find(cv,'uiRoot');var bs=find(cv,'bottles');var holder=bs?bs.getChildByName('bottles'):null;var hud=find(cv,'hudRoot');var nav=find(cv,'navRoot');var out='scene='+sc+' vis='+vs.width.toFixed(0)+'x'+vs.height.toFixed(0)+' bottles='+(holder?holder.children.length:'-');if(gr){out+=' gameS='+gr.scale.x.toFixed(3);}if(ur){var ut=ur.getComponent('cc.UITransform');out+=' uiUT='+ut.width.toFixed(0)+'x'+ut.height.toFixed(0)+' uiS='+ur.scale.x;}if(hud){var wp=hud.getWorldPosition();out+=' hudWp='+wp.y.toFixed(0);}if(nav){var wp2=nav.getWorldPosition();out+=' navWp='+wp2.y.toFixed(0);}return out;})()
sleep:600
eval:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var bs=find(cv,'bottles');var holder=bs.getChildByName('bottles');var b=holder.children[0];var art=b.getChildByName('art')||b;var wp=art.getWorldPosition();var vs=cc.view.getVisibleSize();return 'bottleWp='+wp.x.toFixed(1)+','+wp.y.toFixed(1)+' visCenter='+(vs.width/2)+','+(vs.height/2);})()
jsclick:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var bs=find(cv,'bottles');var holder=bs.getChildByName('bottles');var b=holder.children[0];var art=b.getChildByName('art')||b;var wp=art.getWorldPosition();var cvs=document.querySelector('canvas');var r=cvs.getBoundingClientRect();var vs=cc.view.getVisibleSize();var sx=r.width/vs.width;var sy=r.height/vs.height;return [r.x+wp.x*sx, r.y+r.height-wp.y*sy];})()
sleep:1200
eval:(function(){return 'flips='+window.__tb.G.data.stats.flips;})()
shot:E:/LDC_Cocos_PJ/Cocos3X_2D/点瓶子_竖屏/项目/TapBottle/.workbuddy/_m5_game.png
eval:(function(){var r='';try{window.__tb.ui.settings();r='settings opened';}catch(e){r='ERR:'+e.message;}return r;})()
sleep:1500
eval:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var vs=cc.view.getVisibleSize();var sd=find(cv,'SettingDialog');if(!sd)return 'SettingDialog MISSING';var ut=sd.getComponent('cc.UITransform');var fit=sd.getChildByName('fit');var frame=find(sd,'frame');var fut=frame.getComponent('cc.UITransform');var bb=fut.getBoundingBoxToWorld();var mbb=find(sd,'mask').getComponent('cc.UITransform').getBoundingBoxToWorld();return 'vis='+vs.width.toFixed(0)+'x'+vs.height.toFixed(0)+' sdUT='+ut.width.toFixed(0)+'x'+ut.height.toFixed(0)+' fitScale='+fit.scale.x.toFixed(3)+' maskBBox='+mbb.width.toFixed(0)+'x'+mbb.height.toFixed(0)+' frameBBox='+bb.x.toFixed(0)+','+bb.y.toFixed(0)+' '+bb.width.toFixed(0)+'x'+bb.height.toFixed(0);})()
shot:E:/LDC_Cocos_PJ/Cocos3X_2D/点瓶子_竖屏/项目/TapBottle/.workbuddy/_m5_settings.png
eval:(function(){return 'errors='+JSON.stringify((window.__errs||[]).slice(0,6))+' errCount='+(window.__errs||[]).length;})()
