# 三视流通用验收：分层 + 适配（等比缩放/背景铺满）+ 点击命中（世界坐标）
sleep:4200
eval:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var v=cc.view;var cv=cc.director.getScene().getChildByName('Canvas');var gr=find(cv,'gameRoot');var ur=find(cv,'uiRoot');var bl=find(cv,'bootLayer');var bg=find(cv,'bgLayer');var o=[];o.push('vis='+Math.round(v.getVisibleSize().width)+'x'+Math.round(v.getVisibleSize().height));o.push('vo='+v.getVisibleOrigin().x.toFixed(1)+','+v.getVisibleOrigin().y.toFixed(1));var gs=gr?gr.getWorldScale():null;var us=ur?ur.getWorldScale():null;o.push('gameRoot sc='+(gs?gs.x.toFixed(3):'?')+' uiRoot sc='+(us?us.x.toFixed(3):'?'));o.push('equal='+(gs&&us?Math.abs(gs.x-us.x)<0.001&&Math.abs(gs.y-us.y)<0.001:'?'));var bu=bl?bl.getComponent('cc.UITransform'):null;o.push('bootLayer='+Math.round(v.getVisibleSize().width)+'x'+Math.round(v.getVisibleSize().height)+' vs UT '+(bu?Math.round(bu.width)+'x'+Math.round(bu.height):'?'));var bc=bl?bl.getComponent('Boot'):null;if(bc){bc.shown=bc.target=1;}return o.join(' | ');})()
sleep:1200
jsclick:(function(){return [100,100];})()
sleep:250
jsclick:(function(){var r=document.querySelector('canvas').getBoundingClientRect();return [r.x+r.width/2, r.y+r.height/2];})()
sleep:1800
eval:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var bl=find(cv,'bootLayer');var pr=find(cv,'PageRoot');var o=[];o.push('boot='+(bl?bl.active:'gone'));o.push('pageChildren='+(pr?pr.children.length:'?'));var bs=find(cv,'bottles');var holder=bs?bs.getChildByName('bottles'):null;o.push('bottles='+(holder?holder.children.length:'?'));return o.join(' | ');})()
# 点击第一只瓶子：世界坐标 → UI 坐标(−vo) → CSS 像素（dispatchMouseEvent 的坐标系）
jsclick:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var bs=find(cv,'bottles');var holder=bs?bs.getChildByName('bottles'):null;var b=holder&&holder.children.length?holder.children[0]:null;if(!b)return [10,10];var art=b.getChildByName('art')||b;var wp=art.getWorldPosition();var vo=cc.view.getVisibleOrigin();var vs=cc.view.getVisibleSize();var r=document.querySelector('canvas').getBoundingClientRect();var uiX=wp.x-vo.x,uiY=wp.y-vo.y;var x=uiX*r.width/vs.width;var y=r.height-uiY*r.height/vs.height;return [Math.max(2,Math.min(r.width-2,x)),Math.max(2,Math.min(r.height-2,y))];})()
sleep:1200
eval:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var bs=find(cv,'bottles');var fieldC=bs?bs.getComponent('BottleField'):null;var holder=bs?bs.getChildByName('bottles'):null;var busy=0,tot=0;if(holder){for(var i=0;i<holder.children.length;i++){var b=holder.children[i].getComponent('Bottle');if(b){tot++;if(!b.idle)busy++;}}}var lw=fieldC?fieldC.lastWorld:null;return 'tapResult flips='+window.__tb.G.data.stats.flips+' busy='+busy+'/'+tot+' lastWorld='+(lw?lw.x.toFixed(0)+','+lw.y.toFixed(0):'?');})()
shot:E:/LDC_Cocos_PJ/Cocos3X_2D/点瓶子_竖屏/项目/TapBottle/.workbuddy/_m4_game.png
