sleep:4000
eval:(function(){window.__errs=[];window.addEventListener('error',function(e){window.__errs.push(String(e.message||e.error));});return 'hooked';})()
sleep:400
eval:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var bl=find(cv,'bootLayer');var bc=bl?bl.getComponent('Boot'):null;if(bc){bc.shown=bc.target=1;}return 'forced ready';})()
sleep:1500
jsclick:(function(){var r=document.querySelector('canvas').getBoundingClientRect();return [r.x+r.width/2, r.y+r.height/2];})()
sleep:1500
eval:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var vs=cc.view.getVisibleSize();function info(nm){var n=find(cv,nm);if(!n)return nm+':MISSING';var ws=n.getWorldScale();var ut=n.getComponent('cc.UITransform');var bb=ut?ut.getBoundingBoxToWorld():null;var wp=n.getWorldPosition();return nm+': act='+n.activeInHierarchy+' ws='+ws.x.toFixed(3)+','+ws.y.toFixed(3)+' wp='+wp.x.toFixed(0)+','+wp.y.toFixed(0)+(bb?(' bbox='+bb.x.toFixed(0)+','+bb.y.toFixed(0)+' '+bb.width.toFixed(0)+'x'+bb.height.toFixed(0)):'');}return 'vis='+vs.width.toFixed(0)+'x'+vs.height.toFixed(0)+' || '+['gameRoot','uiRoot','hudRoot','navRoot','belt','worldLayer','bottles','bgLayer'].map(info).join(' || ');})()
eval:(function(){var r='';try{window.__tb.ui.settings();r='settings opened';}catch(e){r='settings ERR:'+e.message;}return r;})()
sleep:1200
eval:(function(){function find(root,nm){if(!root)return null;var q=[root];while(q.length){var n=q.shift();if(n.name===nm)return n;for(var i=0;i<n.children.length;i++)q.push(n.children[i]);}return null;}var cv=cc.director.getScene().getChildByName('Canvas');var vs=cc.view.getVisibleSize();function info(nm){var n=find(cv,nm);if(!n)return nm+':MISSING';var ws=n.getWorldScale();var ut=n.getComponent('cc.UITransform');var bb=ut?ut.getBoundingBoxToWorld():null;return nm+': act='+n.activeInHierarchy+' ws='+ws.x.toFixed(3)+(bb?(' bbox='+bb.x.toFixed(0)+','+bb.y.toFixed(0)+' '+bb.width.toFixed(0)+'x'+bb.height.toFixed(0)):'');}var out='vis='+vs.width.toFixed(0)+'x'+vs.height.toFixed(0)+' || '+['SettingDialog','mask','frame','scroll','ptitle'].map(info).join(' || ');var lb=find(cv,'ptitle');if(lb){var l=lb.getComponent('cc.Label');out+=' || ptitle fs='+(l?l.fontSize:'-')+' scale='+lb.scale.x;}return out;})()
eval:(function(){return 'errors='+JSON.stringify((window.__errs||[]).slice(0,5));})()
shot:E:/LDC_Cocos_PJ/Cocos3X_2D/点瓶子_竖屏/项目/TapBottle/.workbuddy/_diag_settings.png
