sleep:9000
jsclick:(function(){var c=document.getElementById('GameCanvas');var r=c.getBoundingClientRect();return [r.width/2,r.height*0.5];})()
sleep:2500
eval:(function(){var cv=cc.director.getScene().getChildByName('Canvas');var camN=cv.getChildByName('Camera');var cam=camN.getComponent('cc.Camera');var f=window.__tb.field.I;var b=f.bottles[0];var wp=b.node.worldPosition;var sp=cam.worldToScreen(wp);var o={};o.camOrtho=Math.round(cam.orthoHeight*10)/10;o.camWp=[Math.round(camN.worldPosition.x),Math.round(camN.worldPosition.y)];o.bottleWp=[Math.round(wp.x),Math.round(wp.y)];o.bottleScreen=[Math.round(sp.x),Math.round(sp.y)];o.canvasCss=(function(){var c=document.getElementById('GameCanvas');var r=c.getBoundingClientRect();return [Math.round(r.width),Math.round(r.height)];})();var ut=f.node.getComponent('cc.UITransform');var loc=ut.convertToNodeSpaceAR(new cc.Vec3(wp.x,wp.y,0));o.bottleFieldLocal=[Math.round(loc.x),Math.round(loc.y)];o.pointerNow=[Math.round(f.pointer.x),Math.round(f.pointer.y)];return JSON.stringify(o);})()
click:250,410
sleep:600
eval:(function(){var f=window.__tb.field.I;return JSON.stringify({pointerAfterCenterClick:[Math.round(f.pointer.x),Math.round(f.pointer.y)]});})()
eval:(function(){var cv=cc.director.getScene().getChildByName('Canvas');var gr=cv.getChildByName('GameRoot');var hud=gr.getChildByName('contentRoot').getChildByName('shakeHolder').getChildByName('uiLayer').getChildByName('hudRoot');var out=[];for(var i=0;i<hud.children.length;i++){var n=hud.children[i];var ut=n.getComponent('cc.UITransform');out.push(n.name+'@'+Math.round(n.worldPosition.x)+','+Math.round(n.worldPosition.y)+'|'+(ut?Math.round(ut.width)+'x'+Math.round(ut.height):'-')+'|op='+(n.getComponent('cc.UIOpacity')?n.getComponent('cc.UIOpacity').opacity:255)+'|act='+n.activeInHierarchy);}return out.join(' ; ');})()
eval:(function(){var cv=cc.director.getScene().getChildByName('Canvas');var cam=cv.getChildByName('Camera').getComponent('cc.Camera');var wp=new cc.Vec3(0,0,0);var sp=cam.worldToScreen(wp);return JSON.stringify({world0Screen:[Math.round(sp.x),Math.round(sp.y)],winSize:[window.innerWidth,window.innerHeight]});})()
